language: cpp
dist: xenial
sudo: required
compiler:
- gcc
os:
- linux
before_install:
- pip2.7 install --upgrade --user travis pip setuptools wheel virtualenv
- ./scripts/build-dependencies.sh
- echo "--------------------------------------------------------------"
- ls /usr/local/include
script: ./scripts/build.sh
