language: cpp
dist: xenial
sudo: required
compiler:
- gcc
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- ./scripts/build-dependencies.sh
- echo "--------------------------------------------------------------"
- ls /usr/local/include/mesos
script: ./scripts/build.sh
