language: cpp
dist: jessie
sudo: required
compiler:
- gcc
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- ./scripts/build-dependencies.sh
- ./scripts/mesos-headers.sh
script: ./scripts/build.sh
